import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Education from "../components/Education";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import NavigationBar from "../components/NavigationBar";

import Projects from "../components/Projects";
import Skills from "../components/Skills";


export default function Home() {
  return (
    <div className="h-screen overflow-y-scroll overflow-x-hidden z-0">
      <Head>
        <title>Zwelihle Masango</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />

      <main>
        <Hero />
        <About />
        <Education />
        <Skills />
        <Projects />
        <Contact />
      </main>


      <Footer />


    </div>
  );
}
